name: Auto Release
on:
  push:
    tags:
      - 'v*' # Uruchamia się dla każdego taga zaczynającego się od 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body: "Automated release for version ${{ github.ref_name }}"
          prerelease: true # Zaznacza jako pre-release, bo używasz 'b'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
